image: atlassianlabs/buildpack-deps-rust

pipelines:
  branches:
    master:
      - step:
          script:
            - echo "Update Rust toolchain"            ; rustup update
            - echo "Testing"                          ; cargo test
            - echo "Build project"                    ; cargo build --release
