[package]
name = "rustils"
version = "0.0.2"
authors = ["norabx <norabxnetwork@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/NorabX/rustils"
description = "Utilities for rust"

[dependencies]
